{% set name = "uge-drmaa2" %}
{% set version = "8.6.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 979d43c9a09fe8b89555a4bd9193623e7ab9b0f1058fe272bd51d4db5a4e66dc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - drmaa2

about:
  home: https://github.com/gridengine/drmaa2-python
  license: Apache-2.0
  license_family: Apache
  license_file: license.txt
  summary: Python wrapper around the Univar Grid Engine DRMAA2 library.

extra:
  recipe-maintainers:
    - Acribbs
