{% set name = "uge-drmaa2" %}
{% set version = "8.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3011bb08eb3ddb7f7f5dea767f36ec8ebe4dea6f00b94c4da18d2ff7053e1a4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - drmaa2

about:
  home: https://github.com/gridengine/drmaa2-python
  license: Apache-2.0
  license_family: Apache
  license_file: license.txt
  summary: Python wrapper around the Univar Grid Engine DRMAA2 library.

extra:
  recipe-maintainers:
    - Acribbs
