{% set name = "uge-drmaa2" %}
{% set version = "8.6.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 545742c4b7a0a0be9d68ea91dd72f5806ee000278f303a9166774d723ac74ead

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - drmaa2

about:
  home: https://github.com/gridengine/drmaa2-python
  license: Apache-2.0
  license_family: Apache
  license_file: license.txt
  summary: Python wrapper around the Univar Grid Engine DRMAA2 library.

extra:
  recipe-maintainers:
    - Acribbs
